# Configurações da Aplicação Web

# Server
server.port=8080
server.servlet.context-path=/api

# Application Name
spring.application.name=escola-aviacao-api

# Logging
logging.level.root=INFO
logging.level.pt.ipvc.estg=DEBUG
