-- PostgreSQL schema for the Spring Boot API when spring.jpa.hibernate.ddl-auto=validate.
-- Run this once on a clean database before starting the web module.

CREATE TABLE IF NOT EXISTS course (
    id_course INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    duration VARCHAR(50),
    flight_hours INTEGER CHECK (flight_hours IS NULL OR flight_hours > 0),
    theoretical_hours INTEGER CHECK (theoretical_hours IS NULL OR theoretical_hours > 0),
    price DOUBLE PRECISION CHECK (price IS NULL OR price >= 0),
    enrolled INTEGER DEFAULT 0 CHECK (enrolled IS NULL OR enrolled >= 0),
    completed INTEGER DEFAULT 0 CHECK (completed IS NULL OR completed >= 0),
    description VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS instructor (
    id_instructor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    license VARCHAR(50) NOT NULL,
    specialization VARCHAR(200),
    flight_hours INTEGER DEFAULT 0 CHECK (flight_hours IS NULL OR flight_hours >= 0),
    status VARCHAR(20) CHECK (status IS NULL OR status IN ('active', 'inactive')),
    email VARCHAR(100),
    phone VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS aircraft (
    id_aircraft INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration VARCHAR(20) NOT NULL UNIQUE,
    model VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    manufacturing_year INTEGER CHECK (manufacturing_year IS NULL OR manufacturing_year BETWEEN 1903 AND 2100),
    status VARCHAR(20) CHECK (status IS NULL OR status IN ('operational', 'maintenance', 'grounded')),
    flight_hours DOUBLE PRECISION DEFAULT 0 CHECK (flight_hours IS NULL OR flight_hours >= 0),
    last_maintenance DATE,
    next_maintenance DATE,
    location VARCHAR(100),
    fuel_level INTEGER DEFAULT 0 CHECK (fuel_level IS NULL OR fuel_level BETWEEN 0 AND 100),
    notes VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS student (
    id_student INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    nif VARCHAR(20) UNIQUE CHECK (nif IS NULL OR nif ~ '^[0-9]{9}$'),
    birthdate DATE CHECK (birthdate IS NULL OR birthdate <= CURRENT_DATE - INTERVAL '18 years'),
    address VARCHAR(255),
    nationality VARCHAR(50),
    id_course INTEGER NOT NULL REFERENCES course(id_course),
    id_instructor INTEGER REFERENCES instructor(id_instructor),
    status VARCHAR(20) CHECK (status IS NULL OR status IN ('active', 'suspended', 'completed')),
    enrollment_date DATE CHECK (enrollment_date IS NULL OR enrollment_date <= CURRENT_DATE),
    progress INTEGER DEFAULT 0 CHECK (progress IS NULL OR progress BETWEEN 0 AND 100),
    flight_hours DOUBLE PRECISION DEFAULT 0 CHECK (flight_hours IS NULL OR flight_hours >= 0),
    theoretical_hours DOUBLE PRECISION DEFAULT 0 CHECK (theoretical_hours IS NULL OR theoretical_hours >= 0),
    payment_status VARCHAR(20) CHECK (payment_status IS NULL OR payment_status IN ('up_to_date', 'pending', 'overdue')),
    avatar VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS flight (
    id_flight INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_date DATE NOT NULL,
    flight_time TIME,
    duration DOUBLE PRECISION CHECK (duration IS NULL OR duration > 0),
    id_student INTEGER NOT NULL REFERENCES student(id_student) ON DELETE CASCADE,
    id_instructor INTEGER NOT NULL REFERENCES instructor(id_instructor),
    id_aircraft INTEGER NOT NULL REFERENCES aircraft(id_aircraft),
    origin VARCHAR(10) CHECK (origin IS NULL OR origin ~ '^[A-Z]{4}$'),
    destination VARCHAR(10) CHECK (destination IS NULL OR destination ~ '^[A-Z]{4}$'),
    flight_type VARCHAR(50),
    status VARCHAR(20) CHECK (status IS NULL OR status IN ('scheduled', 'completed', 'cancelled')),
    objectives VARCHAR(500),
    notes VARCHAR(500),
    grade VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS evaluation (
    id_evaluation INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_student INTEGER NOT NULL REFERENCES student(id_student) ON DELETE CASCADE,
    id_course INTEGER NOT NULL REFERENCES course(id_course),
    exam_name VARCHAR(200) NOT NULL,
    evaluation_date DATE,
    score INTEGER CHECK (score IS NULL OR score >= 0),
    max_score INTEGER DEFAULT 100 CHECK (max_score IS NULL OR max_score > 0),
    status VARCHAR(20) CHECK (status IS NULL OR status IN ('passed', 'failed', 'scheduled')),
    evaluation_type VARCHAR(50) CHECK (evaluation_type IS NULL OR evaluation_type IN ('theoretical', 'practical', 'simulator')),
    notes VARCHAR(500),
    CONSTRAINT evaluation_score_lte_max CHECK (score IS NULL OR max_score IS NULL OR score <= max_score)
);

CREATE TABLE IF NOT EXISTS payment (
    id_payment INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_student INTEGER NOT NULL REFERENCES student(id_student) ON DELETE CASCADE,
    description VARCHAR(200) NOT NULL,
    amount DOUBLE PRECISION NOT NULL CHECK (amount > 0),
    due_date DATE,
    paid_date DATE CHECK (paid_date IS NULL OR paid_date <= CURRENT_DATE),
    status VARCHAR(20) CHECK (status IS NULL OR status IN ('paid', 'pending', 'overdue')),
    payment_method VARCHAR(50),
    notes VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS maintenance (
    id_maintenance INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_aircraft INTEGER NOT NULL REFERENCES aircraft(id_aircraft) ON DELETE CASCADE,
    maintenance_type VARCHAR(50) NOT NULL,
    description VARCHAR(500) NOT NULL,
    technician VARCHAR(100),
    start_date DATE,
    estimated_end_date DATE,
    actual_end_date DATE,
    status VARCHAR(20) CHECK (status IS NULL OR status IN ('scheduled', 'in_progress', 'waiting_parts', 'completed')),
    priority VARCHAR(20) CHECK (priority IS NULL OR priority IN ('low', 'medium', 'high')),
    cost DOUBLE PRECISION DEFAULT 0 CHECK (cost IS NULL OR cost >= 0),
    notes VARCHAR(500),
    CONSTRAINT maintenance_estimated_after_start CHECK (start_date IS NULL OR estimated_end_date IS NULL OR estimated_end_date >= start_date),
    CONSTRAINT maintenance_actual_after_start CHECK (start_date IS NULL OR actual_end_date IS NULL OR actual_end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS user_account (
    id_user INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'STUDENT')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    id_student INTEGER UNIQUE REFERENCES student(id_student) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_student_course ON student(id_course);
CREATE INDEX IF NOT EXISTS idx_student_status ON student(status);
CREATE INDEX IF NOT EXISTS idx_flight_student ON flight(id_student);
CREATE INDEX IF NOT EXISTS idx_flight_status ON flight(status);
CREATE INDEX IF NOT EXISTS idx_payment_student ON payment(id_student);
CREATE INDEX IF NOT EXISTS idx_payment_status ON payment(status);
CREATE INDEX IF NOT EXISTS idx_maintenance_aircraft ON maintenance(id_aircraft);
CREATE INDEX IF NOT EXISTS idx_maintenance_status ON maintenance(status);
